# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('id_card_number', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployersLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_or_out', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='Out', max_length=5)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, max_length=250, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_recipt_number', models.BigIntegerField(blank=True, null=True)),
                ('truck_plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_containers', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=55, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('price_of_singal_item', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_exports', to='store.Customer')),
            ],
            options={
                'verbose_name_plural': 'Exports',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Imported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_recipt_number', models.BigIntegerField()),
                ('truck_plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_containers', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=55, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('price_of_singal_item', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Imports',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentsOfCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='store.Customer')),
            ],
            options={
                'verbose_name_plural': 'Payments OF Customers',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentsToSuppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payments To Suppliers',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_details', models.TextField(blank=True, null=True)),
                ('container_type_name', models.CharField(max_length=55)),
                ('approximate_weight_container_holds', models.PositiveIntegerField(blank=True, help_text='Make sure the value is in kg!', null=True)),
                ('length', models.PositiveIntegerField(blank=True, help_text='Make sure the value is in inches!', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Make sure the value is in inches!', null=True)),
                ('depth', models.PositiveIntegerField(blank=True, help_text='Make sure the value is in inches!', null=True)),
                ('material_container_made_of', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='containers the store can hold', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store_is_active_from', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='company.Company')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreEmployers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('id_card_number', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='store.Store')),
            ],
            options={
                'verbose_name_plural': 'Employers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('id_card_number', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='store.Store')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Store'),
        ),
        migrations.AddField(
            model_name='paymentstosuppliers',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_supplier_payments', to='store.Store'),
        ),
        migrations.AddField(
            model_name='paymentstosuppliers',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='store.Supplier'),
        ),
        migrations.AddField(
            model_name='paymentsofcustomers',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_customer_payments', to='store.Store'),
        ),
        migrations.AddField(
            model_name='imported',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_imports', to='store.Products'),
        ),
        migrations.AddField(
            model_name='imported',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_imports', to='store.Store'),
        ),
        migrations.AddField(
            model_name='imported',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_imports', to='store.Supplier'),
        ),
        migrations.AddField(
            model_name='exported',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exports', to='store.Products'),
        ),
        migrations.AddField(
            model_name='exported',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_exports', to='store.Store'),
        ),
        migrations.AddField(
            model_name='employersledger',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_payments', to='store.StoreEmployers'),
        ),
        migrations.AddField(
            model_name='employersledger',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_employers_ledger', to='store.Store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.Store'),
        ),
    ]
