# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exported',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imported',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
