# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_active',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
