# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exported',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imported',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsofcustomers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentstosuppliers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
