# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exported',
            name='truck_plate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imported',
            name='truck_plate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
