# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180316_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name_plural': 'Products'},
        ),
    ]
