# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180226_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exported',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Exports'},
        ),
        migrations.AlterModelOptions(
            name='imported',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Imports'},
        ),
        migrations.AlterModelOptions(
            name='paymentsofcustomers',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Payments OF Customers'},
        ),
        migrations.AlterModelOptions(
            name='paymentstosuppliers',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Payments To Suppliers'},
        ),
        migrations.AddField(
            model_name='exported',
            name='product_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='imported',
            name='product_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
