# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180301_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exported',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='imported',
            name='product_name',
        ),
    ]
