# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180302_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='exported',
            name='product_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='imported',
            name='product_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
