# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storeemployers_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersledger',
            name='reason',
            field=models.TextField(max_length=250),
        ),
    ]
